---
- hosts: d2
  tasks:
   - name: Adding DotDeb stretch repository
     apt_repository: repo={{item}}
     with_items:
      - deb http://packages.dotdeb.org stretch all
      - deb-src http://packages.dotdeb.org stretch all
     tags: dotdeb
   - name: Installing DotDeb key
     apt_key: url=http://www.dotdeb.org/dotdeb.gpg
     tags: dotdeb
   - name: Copy apache preference repo
     template:
       src: apache2.pref
       dest: "/etc/apt/preferences.d"
   - name: Copy nginx preference repo
     template:
       src: nginx.pref
       dest: "/etc/apt/preferences.d"
   - name: Installing latest nginx
     apt: name=nginx update_cache=yes state=latest
   - name: APT install latest apache
     apt: name=apache2 update_cache=yes state=latest
   - name: Ensure group test1local exists
     group:
       name: test1local
       state: present
   - name: Ensure group test2local exists
     group:
       name: test2local
       state: present
   - name: Adding the user test1local_admin
     user:
       name: test1local_admin
       shell: /bin/false
       groups: test1local
       append: yes
   - name: Adding the user test2local_admin
     user:
       name: test2local_admin
       shell: /bin/false
       groups: test2local
       append: yes
   - name: Creating directory for test1.local
     file:
       path: /var/www/test1.local/dyn
       state: directory
       mode: 0755
       owner: test1local_admin
       group: test1local
   - name: Creating directory for test1.local
     file:
       path: /var/www/test2.local/dyn
       state: directory
       mode: 0755
       owner: test2local_admin
       group: test2local
   - name: Delete interfaces file
     file:
       path: /etc/network/interfaces
       state: absent
   - name: Copy new  interfaces file
     template:
       src: interfaces
       dest: "/etc/network/"
   - name: Start 1 interface
     command: bash -c "ifup enp0s3:0"
   - name: Start 2 interface
     command: bash -c "ifup enp0s3:1"
   - name: Add test1 to /etc/hosts
     lineinfile:
       path: /etc/hosts
       line: '192.168.1.131 test1.local'
       state: present
   - name: Add test2 to /etc/hosts
     lineinfile:
       path: /etc/hosts
       line: '192.168.1.132 test2.local'
       state: present
   - name: Copy config file for test1 apache site
     template:
       src: apache2/test1.local.conf
       dest: "/etc/apache2/sites-available"
   - name: Copy config file for test2 apache site
     template:
       src: apache2/test2.local.conf
       dest: "/etc/apache2/sites-available"
   - name: Create links 1
     file:
       src: /etc/apache2/sites-available/test1.local.conf
       dest: /etc/apache2/sites-enabled/test1.local.conf
       state: link
   - name: Create links 2
     file:
       src: /etc/apache2/sites-available/test2.local.conf
       dest: /etc/apache2/sites-enabled/test2.local.conf
       state: link
   - name: Ensite 1
     command: bash -c "a2ensite test1.local.conf"
   - name: Ensite 2
     command: bash -c "a2ensite test2.local.conf"
   - name: Copy config file for test1 nginx site
     template:
       src: nginx/test1.local
       dest: "/etc/nginx/sites-available"
   - name: Copy config file for test2 nginx site
     template:
       src: nginx/test2.local
       dest: "/etc/nginx/sites-available"
   - name: Create links 1
     file:
       src: /etc/nginx/sites-available/test1.local
       dest: /etc/nginx/sites-enabled/test1.local
       state: link
   - name: Create links 2
     file:
       src: /etc/nginx/sites-available/test2.local
       dest: /etc/nginx/sites-enabled/test2.local
       state: link
   - name: Replace listen port
     replace:
       path: /etc/apache2/ports.conf
       regexp: '^(NameVirtualHost|Listen)\s+80\s*$'
       replace: 'Listen 81'
   - name: Update repositories cache and install itk package
     apt:
       name: libapache2-mpm-itk
       update_cache: yes
   - name: Reload service apache2
     systemd:
       name: apache2
       state: reloaded
   - name: Reload service nginx
     systemd:
       name: nginx
       state: reloaded
